services:
  - type: web
    name: loja-departamentos-api
    env: node
    plan: free
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: MONGODB_URI
        value: 'mongodb+srv://gabriel:12345@cluster0.j6x47fn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
    runtime: node 20.12.2
